### ISSUE TITLE
Create a project to generate all lint rules for each version

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-yumemi-lints#6]
Create lint rules for each Flutter/Dart version

- dart
  - 2.17.0
    - all.yaml
  - 2.17.1
    - …
- flutter
  - 3.0.0
    - all.yaml
  - 3.0.1
    - …

NOTE:
- Dart version 2.17.0 or higher is required.
- Flutter version 3.0.0 or higher is required.
- YUMEMI Inc. recommended lint rules will be addressed in another Issue.

## Tasks

- [x] Create a base cli project `update_lint_rules`
  - #19
- [x] Implement a process to get all lint rules
  - #20
- [x] Implement a process to extract lint rules for Flutter and Dart
  - #21
- [x] Implement a process to get stable release info of Dart SDK
  - #22
- [x] Implement a process to get stable release info of Flutter SDK
  - #23
- [x] Implement a process to output Dart or Flutter all lint rules to a file
  - #24
- [x] Address a 'duplicate_ignore' warning
  - #25
- [x] Modify the method of determining whether it is a Lint rule for Flutter
  - #26
- [x] Update README of the `update_lint_rules` package
  - #27
